sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t wicochandra/udemy-deploy-multi-client ./client

script:
  - docker run -e CI=true wicochandra/udemy-deploy-multi-client npm run test -- --coverage

after_success:
  # Build all production docker images
  - docker build -t wicochandra/udemy-deploy-multi-client ./client
  - docker build -t wicochandra/udemy-deploy-multi-nginx ./nginx
  - docker build -t wicochandra/udemy-deploy-multi-server ./server
  - docker build -t wicochandra/udemy-deploy-multi-worker ./worker
  # Login to Docker Hub
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  # push images to hub.docker.com
  - docker push wicochandra/udemy-deploy-multi-client
  - docker push wicochandra/udemy-deploy-multi-nginx
  - docker push wicochandra/udemy-deploy-multi-server
  - docker push wicochandra/udemy-deploy-multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "udemy-multi-docker"
  env: "Udemymultidocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-280037490921"
  bucket_path: "udemy-multi-docker"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master